{Device_Name: cs42l42, Simulated_System: true, SystemFile: cdb42l42.xml, Target_SystemName: SimSystem4,
  linkPath: 'C:/Program Files/CirrusLogic/SoundClearStudio_1.1/link/bin/', log_level: DEBUG,
  log_path: test_fwk/unit_tests/lib_tests/logs, proj_path: test_fwk/unit_tests/lib_tests}
